version: '3'

networks:
  salary-hero:
    driver: bridge

services:
  database: 
    image: postgres:latest
    container_name: salary-hero-database
    restart: always
    volumes:
      - ./docker/postgres-db-volume:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    networks:
      - salary-hero
    ports:
      - 5432:5432

  cache: 
    image: redis:latest
    container_name: salary-hero-cache
    restart: always
    volumes:
      - ./docker/redis-data:/data
    networks:
      - salary-hero
    ports:
      - 6379:6379

  app: 
    image: node:latest
    container_name: salary-hero-app
    restart: always
    build: .
    volumes:
      - .:/app
    working_dir: /app
    env_file:
      - .env
    environment:
      - APP_PORT=${APP_PORT}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_HOST=database
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
      - CACHE_PORT=${CACHE_PORT}
      - CACHE_HOST=cache
    ports:
      - ${APP_PORT}:3000
    networks:
      - salary-hero
    depends_on:
      - cache
      - database
    command: bash -c "npm run start:dev"
    
    
    